<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Login test" duration-ms="33589" started-at="2017-11-14T13:18:13Z" finished-at="2017-11-14T13:18:46Z">
    <groups>
    </groups>
    <test name="Login test with valid credentials." duration-ms="14951" started-at="2017-11-14T13:18:13Z" finished-at="2017-11-14T13:18:27Z">
      <class name="tests.Login_test_valid_credentials">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:tests.Login_test_valid_credentials@6a4f787b]" name="beforeClass" is-config="true" duration-ms="11058" started-at="2017-11-14T15:18:13Z" finished-at="2017-11-14T15:18:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Login_test_with_valid_credentials()[pri:0, instance:tests.Login_test_valid_credentials@6a4f787b]" name="Login_test_with_valid_credentials" duration-ms="1978" started-at="2017-11-14T15:18:24Z" finished-at="2017-11-14T15:18:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_test_with_valid_credentials -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:tests.Login_test_valid_credentials@6a4f787b]" name="afterClass" is-config="true" duration-ms="1866" started-at="2017-11-14T15:18:26Z" finished-at="2017-11-14T15:18:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.Login_test_valid_credentials@6a4f787b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-11-14T15:18:26Z" finished-at="2017-11-14T15:18:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_test_with_valid_credentials status=SUCCESS method=Login_test_valid_credentials.Login_test_with_valid_credentials()[pri:0, instance:tests.Login_test_valid_credentials@6a4f787b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.Login_test_valid_credentials -->
    </test> <!-- Login test with valid credentials. -->
    <test name="Login test with invalid credentials." duration-ms="18611" started-at="2017-11-14T13:18:28Z" finished-at="2017-11-14T13:18:46Z">
      <class name="tests.Login_test_invalid_credentials">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:tests.Login_test_invalid_credentials@14bf9759]" name="beforeClass" is-config="true" duration-ms="5735" started-at="2017-11-14T15:18:28Z" finished-at="2017-11-14T15:18:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Login_test_with_invalid_credentials()[pri:0, instance:tests.Login_test_invalid_credentials@14bf9759]" name="Login_test_with_invalid_credentials" duration-ms="11050" started-at="2017-11-14T15:18:33Z" finished-at="2017-11-14T15:18:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at pages.Login_Page.Check_welcome_text(Login_Page.java:58)
	at tests.Login_test_invalid_credentials.Login_test_with_invalid_credentials(Login_test_invalid_credentials.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_test_with_invalid_credentials -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:tests.Login_test_invalid_credentials@14bf9759]" name="afterMethod" is-config="true" duration-ms="538" started-at="2017-11-14T15:18:44Z" finished-at="2017-11-14T15:18:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login_test_with_invalid_credentials status=FAILURE method=Login_test_invalid_credentials.Login_test_with_invalid_credentials()[pri:0, instance:tests.Login_test_invalid_credentials@14bf9759] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:tests.Login_test_invalid_credentials@14bf9759]" name="afterClass" is-config="true" duration-ms="1283" started-at="2017-11-14T15:18:45Z" finished-at="2017-11-14T15:18:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- tests.Login_test_invalid_credentials -->
    </test> <!-- Login test with invalid credentials. -->
  </suite> <!-- Login test -->
</testng-results>
